services:
  task2:
    build: .
    ports:
      - "4201:4201"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    stdin_open: true
    tty: true
    command: /bin/sh -c "npm install && npm start"
